name: Release

on:
  push:
    tags:
      - "v**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup required tools"
        run: apt-get update && apt-get install -y zstd p7zip-full

      - name: "Build the environment"
        run: ./build.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: env.zip
